name: Documentation

on:
  push:
    branches:
    - main

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:

    - name: Install Python
      uses: actions/setup-python@v2

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Install System Requirements for Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg libsm6 libxext6 -y
        pip install --upgrade pip
        pip install '.[test,docs]'
        pip install av --no-binary av
        pip install https://github.com/tobiipro/g3pylib.git --no-deps

    - name: Install ETTK
      run: |
          python3 -m pip install .

    - name: Install Python Dependencies
      run: |
        cd docs/
        pip install -r requirements.txt
        cd ..

    - name: Build and Commit
      uses: sphinx-notes/pages@v2

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
